using System.Collections.Immutable;
using System.Text;
using AtomUI.Generator.Diagnostics;
using AtomUI.Generator.LinkedRegistration.Manifest;
using AtomUI.Generator.LinkedRegistration.Model;
using AtomUI.LinkedRegistration.Protocol;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace AtomUI.Generator.LinkedRegistration;

[Generator]
public sealed class LinkedRegistrationPackageManifestGenerator : IIncrementalGenerator
{
    private const string AotTrimUnitAttributeFullName = "AtomUI.Registration.AotTrimUnitAttribute";
    private const string ExplicitUnitConflictReason = "ExplicitUnitConflict";
    private const string FileUnitConflictReason = "FileUnitConflict";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = LinkedCSharpUsageCandidateProvider.Create(context).Collect();
        var input = context.CompilationProvider.Combine(candidates)
                           .Combine(context.AnalyzerConfigOptionsProvider);
        context.RegisterSourceOutput(input, static (productionContext, value) =>
            Generate(
                productionContext,
                value.Left.Left,
                value.Left.Right,
                value.Right));
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<LinkedCSharpUsageCandidate> candidates,
        AnalyzerConfigOptionsProvider optionsProvider)
    {
        var assemblyName = compilation.AssemblyName ?? "AtomUI";
        var packageId = LinkedRegistrationOptions.GetDeclaredPackageId(optionsProvider);
        if (packageId.Length == 0 ||
            LinkedRegistrationOptions.GetRegistrationGranularity(optionsProvider, out _) !=
            RegistrationUnitGranularity.Directory)
        {
            context.AddSource(
                "LinkedRegistrationPackageAnalysis.g.cs",
                GeneratedSourceText.From("// <auto-generated />\n#nullable enable\n"));
            return;
        }

        var projectDirectory = LinkedRegistrationOptions.GetProjectDirectory(optionsProvider);
        var typeUnits = BuildTypeUnitMap(
            compilation,
            packageId,
            projectDirectory,
            optionsProvider,
            out var knownUnits,
            out var controlTypes,
            out var fileUnitOverrides,
            out var unitConflicts);
        foreach (var conflict in unitConflicts)
        {
            ReportUnitConflict(context, optionsProvider, conflict);
        }
        var edges = new HashSet<UnitEdge>(UnitEdgeComparer.Instance);
        var rootUnits = new HashSet<string>(StringComparer.Ordinal);
        var fallbacks = new HashSet<Fallback>(FallbackComparer.Instance);

        if (candidates.Length > LinkedRegistrationAnalysisBudget.MaxSourceCandidates ||
            knownUnits.Count > LinkedRegistrationAnalysisBudget.MaxRegistrationUnits)
        {
            fallbacks.Add(new Fallback(
                packageId,
                "AnalysisBudgetExceeded",
                assemblyName,
                0,
                0,
                Location.None));
        }
        else
        {
            var treesByPath = compilation.SyntaxTrees
                .Where(static tree => tree.FilePath.Length != 0)
                .GroupBy(static tree => tree.FilePath, StringComparer.Ordinal)
                .ToDictionary(
                    static group => group.Key,
                    static group => group.First(),
                    StringComparer.Ordinal);
            foreach (var candidate in candidates.OrderBy(
                         static item => item.Source,
                         StringComparer.Ordinal).ThenBy(static item => item.SpanStart)
                                              .ThenBy(static item => item.Kind)
                                              .ThenBy(static item => item.Identity, StringComparer.Ordinal))
            {
                context.CancellationToken.ThrowIfCancellationRequested();
                if (candidate.Kind == LinkedCSharpUsageCandidateKind.Dynamic)
                {
                    fallbacks.Add(new Fallback(
                        packageId,
                        LinkedRegistrationProtocol.FallbackReasonDynamicInvocation,
                        NormalizeSourcePath(candidate.Source, projectDirectory),
                        candidate.Line,
                        candidate.Column,
                        candidate.CreateLocation()));
                    continue;
                }

                var targetType = candidate.Kind == LinkedCSharpUsageCandidateKind.Type
                    ? candidate.Identity
                    : candidate.ContainingTypeIdentity;
                if (!typeUnits.TryGetValue(targetType, out var targetUnitId))
                {
                    if (controlTypes.Contains(targetType))
                    {
                        fallbacks.Add(new Fallback(
                            packageId,
                            "UnresolvedOwner",
                            NormalizeSourcePath(candidate.Source, projectDirectory),
                            candidate.Line,
                            candidate.Column,
                            candidate.CreateLocation()));
                    }
                    continue;
                }

                var sourceUnitId = GetUnitIdForSource(
                    candidate.Source,
                    packageId,
                    projectDirectory,
                    optionsProvider,
                    treesByPath,
                    fileUnitOverrides,
                    knownUnits);
                if (sourceUnitId is null)
                {
                    if (candidate.Kind == LinkedCSharpUsageCandidateKind.Type)
                    {
                        rootUnits.Add(targetUnitId);
                    }
                    continue;
                }
                if (string.Equals(sourceUnitId, targetUnitId, StringComparison.Ordinal))
                {
                    continue;
                }
                if (candidate.IsInterfaceDispatch)
                {
                    continue;
                }
                if (candidate.IsOpenDispatch)
                {
                    fallbacks.Add(new Fallback(
                        packageId,
                        "UnresolvedOwner",
                        NormalizeSourcePath(candidate.Source, projectDirectory),
                        candidate.Line,
                        candidate.Column,
                        candidate.CreateLocation()));
                    continue;
                }

                edges.Add(new UnitEdge(
                    packageId,
                    sourceUnitId,
                    targetUnitId,
                    candidate.Kind == LinkedCSharpUsageCandidateKind.Call
                        ? LinkedUnitEdgeEvidenceKind.CSharpCall
                        : LinkedUnitEdgeEvidenceKind.CSharpType));
                if (edges.Count > LinkedRegistrationAnalysisBudget.MaxUnitEdges)
                {
                    edges.Clear();
                    rootUnits.Clear();
                    fallbacks.Add(new Fallback(
                        packageId,
                        "AnalysisBudgetExceeded",
                        assemblyName,
                        0,
                        0,
                        Location.None));
                    break;
                }
            }
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        foreach (var edge in edges.OrderBy(static edge => edge.SourceUnitId, StringComparer.Ordinal)
                                  .ThenBy(static edge => edge.TargetUnitId, StringComparer.Ordinal)
                                  .ThenBy(static edge => edge.EvidenceKind))
        {
            LinkedRegistrationMetadataWriter.Write(
                source,
                new LinkedUnitEdgeManifestRecord(
                    edge.PackageId,
                    edge.SourceUnitId,
                    edge.TargetUnitId,
                    edge.EvidenceKind));
        }
        foreach (var unitId in rootUnits.OrderBy(static unitId => unitId, StringComparer.Ordinal))
        {
            LinkedRegistrationMetadataWriter.Write(
                source,
                new LinkedRootUnitManifestRecord(packageId, unitId));
        }
        foreach (var fallback in fallbacks.OrderBy(static item => item.Source, StringComparer.Ordinal)
                                          .ThenBy(static item => item.Line)
                                          .ThenBy(static item => item.Column)
                                          .ThenBy(static item => item.Reason, StringComparer.Ordinal))
        {
            LinkedRegistrationMetadataWriter.Write(
                source,
                new LinkedFallbackManifestRecord(
                    fallback.PackageId,
                    fallback.Reason,
                    fallback.Source,
                    fallback.Line,
                    fallback.Column));
            ReportFallback(context, optionsProvider, fallback);
        }
        context.AddSource(
            "LinkedRegistrationPackageAnalysis.g.cs",
            GeneratedSourceText.From(source.ToString()));
    }

    private static Dictionary<string, string> BuildTypeUnitMap(
        Compilation compilation,
        string packageId,
        string projectDirectory,
        AnalyzerConfigOptionsProvider optionsProvider,
        out HashSet<string> knownUnits,
        out HashSet<string> controlTypes,
        out Dictionary<string, string> fileUnitOverrides,
        out List<UnitConflict> unitConflicts)
    {
        var types = GetTypes(compilation.Assembly.GlobalNamespace).ToArray();
        var candidateUnits = new Dictionary<INamedTypeSymbol, string?>(SymbolEqualityComparer.Default);
        knownUnits = new HashSet<string>(StringComparer.Ordinal);
        controlTypes = new HashSet<string>(StringComparer.Ordinal);
        fileUnitOverrides = new Dictionary<string, string>(StringComparer.Ordinal);
        unitConflicts = new List<UnitConflict>();
        var reportedConflicts = new HashSet<string>(StringComparer.Ordinal);
        var conflictedFiles = new HashSet<string>(StringComparer.Ordinal);
        foreach (var type in types)
        {
            var attributeUnitName = GetAotTrimUnitName(type);
            if (attributeUnitName is not null)
            {
                CollectAotTrimUnitDeclarations(
                    type,
                    attributeUnitName,
                    packageId,
                    optionsProvider,
                    fileUnitOverrides,
                    conflictedFiles,
                    unitConflicts,
                    reportedConflicts);
            }
            var unitId = GetUnitIdForType(
                type,
                packageId,
                projectDirectory,
                optionsProvider,
                attributeUnitName);
            candidateUnits[type] = unitId;
            if (IsControlType(type))
            {
                controlTypes.Add(LinkedRegistrationSymbolName.GetTypeMetadataName(type));
                if (unitId is not null)
                {
                    knownUnits.Add(unitId);
                }
            }
        }

        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var pair in candidateUnits)
        {
            if (pair.Value is not null && knownUnits.Contains(pair.Value))
            {
                result[LinkedRegistrationSymbolName.GetTypeMetadataName(pair.Key)] = pair.Value;
            }
        }
        return result;
    }

    private static void CollectAotTrimUnitDeclarations(
        INamedTypeSymbol type,
        string attributeUnitName,
        string packageId,
        AnalyzerConfigOptionsProvider optionsProvider,
        Dictionary<string, string> fileUnitOverrides,
        HashSet<string> conflictedFiles,
        List<UnitConflict> unitConflicts,
        HashSet<string> reportedConflicts)
    {
        var attributeUnit = RegistrationUnitId.Create(
            packageId,
            RegistrationUnitGranularity.Directory,
            null,
            null,
            type.Name,
            attributeUnitName);
        var location = GetAotTrimUnitLocation(type);
        var typeDisplay = LinkedRegistrationSymbolName.GetTypeMetadataName(type);

        foreach (var reference in type.DeclaringSyntaxReferences)
        {
            if (optionsProvider.GetOptions(reference.SyntaxTree).TryGetValue(
                    "build_metadata.Compile.AtomUIRegistrationUnit",
                    out var metadataUnit) &&
                !string.IsNullOrWhiteSpace(metadataUnit))
            {
                var qualifiedMetadataUnit = RegistrationUnitId.Create(
                    packageId,
                    RegistrationUnitGranularity.Directory,
                    null,
                    null,
                    type.Name,
                    metadataUnit);
                if (!string.Equals(qualifiedMetadataUnit, attributeUnit, StringComparison.Ordinal) &&
                    reportedConflicts.Add(
                        $"{ExplicitUnitConflictReason}|{typeDisplay}|{reference.SyntaxTree.FilePath}"))
                {
                    unitConflicts.Add(new UnitConflict(
                        ExplicitUnitConflictReason,
                        location,
                        attributeUnitName,
                        metadataUnit,
                        typeDisplay));
                }
            }

            var filePath = reference.SyntaxTree.FilePath;
            if (filePath.Length == 0 || conflictedFiles.Contains(filePath))
            {
                continue;
            }
            if (fileUnitOverrides.TryGetValue(filePath, out var existingUnit))
            {
                if (!string.Equals(existingUnit, attributeUnit, StringComparison.Ordinal))
                {
                    if (reportedConflicts.Add($"{FileUnitConflictReason}|{filePath}"))
                    {
                        unitConflicts.Add(new UnitConflict(
                            FileUnitConflictReason,
                            location,
                            filePath,
                            existingUnit,
                            attributeUnit));
                    }
                    fileUnitOverrides.Remove(filePath);
                    conflictedFiles.Add(filePath);
                }
            }
            else
            {
                fileUnitOverrides[filePath] = attributeUnit;
            }
        }
    }

    private static string? GetAotTrimUnitName(INamedTypeSymbol type)
    {
        foreach (var attributeData in type.GetAttributes())
        {
            if (attributeData.AttributeClass?.ToDisplayString() != AotTrimUnitAttributeFullName)
            {
                continue;
            }
            if (attributeData.ConstructorArguments.Length == 1 &&
                attributeData.ConstructorArguments[0].Value is string unitName &&
                unitName.Length != 0)
            {
                return unitName;
            }
            return null;
        }
        return null;
    }

    private static Location? GetAotTrimUnitLocation(INamedTypeSymbol type)
    {
        foreach (var attributeData in type.GetAttributes())
        {
            if (attributeData.AttributeClass?.ToDisplayString() != AotTrimUnitAttributeFullName)
            {
                continue;
            }
            var reference = attributeData.ApplicationSyntaxReference;
            if (reference is not null)
            {
                return Location.Create(reference.SyntaxTree, reference.Span);
            }
        }
        return type.Locations.FirstOrDefault();
    }

    private static string? GetUnitIdForType(
        INamedTypeSymbol type,
        string packageId,
        string projectDirectory,
        AnalyzerConfigOptionsProvider optionsProvider,
        string? attributeUnitName)
    {
        var candidates = type.DeclaringSyntaxReferences.Select(reference =>
                CreateUnitId(
                    reference.SyntaxTree,
                    packageId,
                    projectDirectory,
                    type.Name,
                    optionsProvider,
                    attributeUnitName))
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        return candidates.Length == 1 ? candidates[0] : null;
    }

    private static string? GetUnitIdForSource(
        string source,
        string packageId,
        string projectDirectory,
        AnalyzerConfigOptionsProvider optionsProvider,
        IReadOnlyDictionary<string, SyntaxTree> treesByPath,
        IReadOnlyDictionary<string, string> fileUnitOverrides,
        ISet<string> knownUnits)
    {
        if (!treesByPath.TryGetValue(source, out var tree))
        {
            return null;
        }
        if (fileUnitOverrides.TryGetValue(tree.FilePath, out var overrideUnit))
        {
            return knownUnits.Contains(overrideUnit) ? overrideUnit : null;
        }
        var unitId = CreateUnitId(
            tree,
            packageId,
            projectDirectory,
            Path.GetFileNameWithoutExtension(source),
            optionsProvider);
        return knownUnits.Contains(unitId) ? unitId : null;
    }

    private static string CreateUnitId(
        SyntaxTree tree,
        string packageId,
        string projectDirectory,
        string fallbackName,
        AnalyzerConfigOptionsProvider optionsProvider,
        string? attributeUnit = null)
    {
        var explicitUnit = attributeUnit;
        if (explicitUnit is null)
        {
            optionsProvider.GetOptions(tree).TryGetValue(
                "build_metadata.Compile.AtomUIRegistrationUnit",
                out explicitUnit);
        }
        return RegistrationUnitId.Create(
            packageId,
            RegistrationUnitGranularity.Directory,
            tree.FilePath,
            projectDirectory,
            fallbackName,
            explicitUnit);
    }

    private static IEnumerable<INamedTypeSymbol> GetTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers().OrderBy(
                     static type => type.MetadataName,
                     StringComparer.Ordinal))
        {
            yield return type;
            foreach (var nested in GetNestedTypes(type))
            {
                yield return nested;
            }
        }
        foreach (var child in ns.GetNamespaceMembers().OrderBy(
                     static child => child.Name,
                     StringComparer.Ordinal))
        {
            foreach (var type in GetTypes(child))
            {
                yield return type;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers().OrderBy(
                     static item => item.MetadataName,
                     StringComparer.Ordinal))
        {
            yield return nested;
            foreach (var descendant in GetNestedTypes(nested))
            {
                yield return descendant;
            }
        }
    }

    private static bool IsControlType(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.BaseType)
        {
            if (LinkedRegistrationSymbolName.GetTypeMetadataName(current.OriginalDefinition) ==
                "Avalonia.Controls.Control")
            {
                return true;
            }
        }
        return false;
    }

    private static string NormalizeSourcePath(string path, string projectDirectory)
    {
        var normalized = path.Replace('\\', '/');
        var root = projectDirectory.Replace('\\', '/').TrimEnd('/');
        if (root.Length != 0 && normalized.StartsWith(root + "/", StringComparison.Ordinal))
        {
            return normalized.Substring(root.Length + 1);
        }
        return normalized.Length == 0 ? "<Unknown>" : normalized;
    }

    private static void ReportUnitConflict(
        SourceProductionContext context,
        AnalyzerConfigOptionsProvider optionsProvider,
        UnitConflict conflict)
    {
        var descriptor = string.Equals(conflict.Reason, FileUnitConflictReason, StringComparison.Ordinal)
            ? AtomUIDiagnosticDescriptors.LinkedFileUnitConflict
            : AtomUIDiagnosticDescriptors.LinkedExplicitUnitConflict;
        if (LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider))
        {
            descriptor = new DiagnosticDescriptor(
                descriptor.Id,
                descriptor.Title,
                descriptor.MessageFormat,
                descriptor.Category,
                DiagnosticSeverity.Error,
                descriptor.IsEnabledByDefault,
                descriptor.Description,
                descriptor.HelpLinkUri,
                descriptor.CustomTags.ToArray());
        }
        context.ReportDiagnostic(Diagnostic.Create(
            descriptor,
            conflict.Location,
            conflict.FirstArg,
            conflict.SecondArg,
            conflict.ThirdArg));
    }

    private static void ReportFallback(
        SourceProductionContext context,
        AnalyzerConfigOptionsProvider optionsProvider,
        Fallback fallback)
    {
        var descriptor = string.Equals(
            fallback.Reason,
            LinkedRegistrationProtocol.FallbackReasonDynamicInvocation,
            StringComparison.Ordinal)
            ? AtomUIDiagnosticDescriptors.LinkedDynamicUsageUncovered
            : AtomUIDiagnosticDescriptors.LinkedDynamicUsageWidened;
        if (LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider))
        {
            descriptor = new DiagnosticDescriptor(
                descriptor.Id,
                descriptor.Title,
                descriptor.MessageFormat,
                descriptor.Category,
                DiagnosticSeverity.Error,
                descriptor.IsEnabledByDefault,
                descriptor.Description,
                descriptor.HelpLinkUri,
                descriptor.CustomTags.ToArray());
        }
        context.ReportDiagnostic(Diagnostic.Create(
            descriptor,
            fallback.Location,
            fallback.Reason,
            fallback.PackageId));
    }

    private sealed class UnitConflict
    {
        internal UnitConflict(
            string reason,
            Location? location,
            string firstArg,
            string secondArg,
            string thirdArg)
        {
            Reason = reason;
            Location = location;
            FirstArg = firstArg;
            SecondArg = secondArg;
            ThirdArg = thirdArg;
        }

        internal string Reason { get; }
        internal Location? Location { get; }
        internal string FirstArg { get; }
        internal string SecondArg { get; }
        internal string ThirdArg { get; }
    }

    private sealed class UnitEdge
    {
        internal UnitEdge(
            string packageId,
            string sourceUnitId,
            string targetUnitId,
            LinkedUnitEdgeEvidenceKind evidenceKind)
        {
            PackageId = packageId;
            SourceUnitId = sourceUnitId;
            TargetUnitId = targetUnitId;
            EvidenceKind = evidenceKind;
        }

        internal string PackageId { get; }
        internal string SourceUnitId { get; }
        internal string TargetUnitId { get; }
        internal LinkedUnitEdgeEvidenceKind EvidenceKind { get; }
    }

    private sealed class UnitEdgeComparer : IEqualityComparer<UnitEdge>
    {
        internal static UnitEdgeComparer Instance { get; } = new();

        public bool Equals(UnitEdge? x, UnitEdge? y)
        {
            return x is not null && y is not null &&
                   x.PackageId == y.PackageId &&
                   x.SourceUnitId == y.SourceUnitId &&
                   x.TargetUnitId == y.TargetUnitId &&
                   x.EvidenceKind == y.EvidenceKind;
        }

        public int GetHashCode(UnitEdge obj)
        {
            unchecked
            {
                var hash = StringComparer.Ordinal.GetHashCode(obj.PackageId);
                hash = (hash * 397) ^ StringComparer.Ordinal.GetHashCode(obj.SourceUnitId);
                hash = (hash * 397) ^ StringComparer.Ordinal.GetHashCode(obj.TargetUnitId);
                return (hash * 397) ^ (int)obj.EvidenceKind;
            }
        }
    }

    private sealed class Fallback
    {
        internal Fallback(
            string packageId,
            string reason,
            string source,
            int line,
            int column,
            Location location)
        {
            PackageId = packageId;
            Reason = reason;
            Source = source;
            Line = line;
            Column = column;
            Location = location;
        }

        internal string PackageId { get; }
        internal string Reason { get; }
        internal string Source { get; }
        internal int Line { get; }
        internal int Column { get; }
        internal Location Location { get; }
    }

    private sealed class FallbackComparer : IEqualityComparer<Fallback>
    {
        internal static FallbackComparer Instance { get; } = new();

        public bool Equals(Fallback? x, Fallback? y)
        {
            return x is not null && y is not null &&
                   x.PackageId == y.PackageId &&
                   x.Reason == y.Reason &&
                   x.Source == y.Source &&
                   x.Line == y.Line &&
                   x.Column == y.Column;
        }

        public int GetHashCode(Fallback obj)
        {
            unchecked
            {
                var hash = StringComparer.Ordinal.GetHashCode(obj.PackageId);
                hash = (hash * 397) ^ StringComparer.Ordinal.GetHashCode(obj.Reason);
                hash = (hash * 397) ^ StringComparer.Ordinal.GetHashCode(obj.Source);
                hash = (hash * 397) ^ obj.Line;
                return (hash * 397) ^ obj.Column;
            }
        }
    }
}
