<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
    <ItemGroup>
        <PackageReference Include="AtomUI.Desktop.Controls" Version="$(AtomUIFixtureVersion)" />
        <PackageReference Include="Avalonia.Headless" Version="12.1.3" />
        <ProjectReference Include="../Author/Author.csproj" />
    </ItemGroup>
</Project>
