using AtomUI.Generator.Diagnostics;
using System.Text;
using Microsoft.CodeAnalysis;

namespace AtomUI.Generator;

[Generator]
public sealed class ControlPackageBootstrapGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var output = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (input, _) => Build(input.Left, input.Right.GlobalOptions))
            .WithTrackingName("ControlPackageBootstrap");
        context.RegisterSourceOutput(output, static (context, result) => result.Write(context));
    }

    private static GenerationResult Build(Compilation compilation, Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions options)
    {
        var output = new GenerationOutput();
        var markerType = compilation.GetTypeByMetadataName("AtomUI.Registration.ControlPackageMarkerAttribute");
        if (markerType is null)
        {
            return output.Freeze();
        }

        var packages = new Dictionary<string, (string Assembly, string Group)>(StringComparer.Ordinal);
        var discovered = new List<(string Id, string Assembly, string Group)>();
        var visited = new HashSet<IAssemblySymbol>(SymbolEqualityComparer.Default);
        var pending = new Queue<IAssemblySymbol>(compilation.SourceModule.ReferencedAssemblySymbols);
        while (pending.Count != 0)
        {
            var assembly = pending.Dequeue();
            if (!visited.Add(assembly))
            {
                continue;
            }

            foreach (var module in assembly.Modules)
            {
                foreach (var reference in module.ReferencedAssemblySymbols)
                {
                    pending.Enqueue(reference);
                }
            }

            var markers = assembly.GetAttributes().Where(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, markerType)).ToArray();
            if (markers.Length == 0)
            {
                continue;
            }

            if (markers.Length != 1 || markers[0].ConstructorArguments.Length != 3 ||
                markers[0].ConstructorArguments[0].Value is not string id || string.IsNullOrWhiteSpace(id) ||
                markers[0].ConstructorArguments[1].Value is not INamedTypeSymbol group ||
                markers[0].ConstructorArguments[2].Value is not int abi || abi != 1 ||
                !SymbolEqualityComparer.Default.Equals(group.ContainingAssembly, assembly) || !PublicClosed(group))
            {
                output.ReportDiagnostic(Diagnostic.Create(AtomUIDiagnosticDescriptors.RegistrationUnsupportedBackend, Location.None, assembly.Identity.GetDisplayName()));
                continue;
            }
            discovered.Add((id, assembly.Identity.GetDisplayName(), group.ToDisplayString(GeneratorSymbolDisplay.FullyQualifiedType)));
        }
        foreach (var marker in discovered.OrderBy(p => p.Id, StringComparer.Ordinal).ThenBy(p => p.Assembly, StringComparer.Ordinal))
        {
            var item = (marker.Assembly, marker.Group);
            if (packages.TryGetValue(marker.Id, out var old) && old != item)
            {
                output.ReportDiagnostic(Diagnostic.Create(AtomUIDiagnosticDescriptors.RegistrationIdentityConflict, Location.None, marker.Id + ": " + old.Assembly + " / " + item.Assembly));
            }
            else
            {
                packages[marker.Id] = item;
            }
        }
        foreach (var group in packages.GroupBy(p => p.Value.Group, StringComparer.Ordinal).Where(g => g.Select(p => p.Value.Assembly).Distinct().Count() > 1))
        {
            output.ReportDiagnostic(Diagnostic.Create(AtomUIDiagnosticDescriptors.RegistrationIdentityConflict, Location.None, "Group identity collision: " + group.Key));
        }

        if (packages.Count == 0)
        {
            return output.Freeze();
        }
        if (!RegistrationFrameworkResolver.TryResolve(compilation, options, out var framework, out var error))
        {
            output.ReportDiagnostic(Diagnostic.Create(AtomUIDiagnosticDescriptors.RegistrationUnsupportedBackend, Location.None, error));
            return output.Freeze();
        }
        if (framework == AtomUI.Build.Tasks.Registration.RegistrationFrameworkFamily.OfficialTypeMap)
        {
            var source = new StringBuilder("// <auto-generated />\n");
            foreach (var package in packages.OrderBy(p => p.Key, StringComparer.Ordinal))
            {
                source.Append("[assembly: global::System.Runtime.InteropServices.TypeMapAssemblyTarget<").Append(package.Value.Group)
                    .Append(">(").Append(RegistrationNames.Literal(package.Value.Assembly)).AppendLine(")]");
            }

            output.AddSource("GeneratedControlPackageBootstrap.g.cs", GeneratedSourceText.From(source.ToString()));
        }
        return output.Freeze();
    }
    private static bool PublicClosed(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility != Accessibility.Public || current.Arity != 0)
            {
                return false;
            }
        }

        return true;
    }
}
