using System.Text;
using AtomUI.Generator.Diagnostics;
using Microsoft.CodeAnalysis;

namespace AtomUI.Generator;

internal static class TypeMapRegistrationWriter
{
    internal static void Write(
        GenerationOutput context,
        RegistrationPackage package,
        Func<string, string>? keyHash = null,
        bool supportsTypeMap = true)
    {
        if (package.Controls.Count == 0 && package.Assets.Count == 0)
        {
            return;
        }

        var groupName = "ControlPackageGroup_" + RegistrationNames.Hash(package.AssemblyIdentity);
        var (mapEntries, collisions) = CreateMapEntries(package, groupName, keyHash ?? RegistrationNames.Hash);
        if (collisions.Count != 0)
        {
            foreach (var collision in collisions)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    AtomUIDiagnosticDescriptors.RegistrationIdentityConflict,
                    Location.None,
                    collision));
            }
            return;
        }
        if (!supportsTypeMap && !ConditionalRegistrationWriter.Write(context, package, groupName))
        {
            return;
        }
        context.AddSource(
            "GeneratedTypeMapRegistration.g.cs",
            GeneratedSourceText.From(Build(package, groupName, mapEntries, supportsTypeMap)));
    }

    private static string Build(RegistrationPackage package, string groupName, IReadOnlyList<TypeMapEntry> mapEntries,
        bool supportsTypeMap)
    {
        var source = new StringBuilder("// <auto-generated />\n#nullable enable\n");
        var group = "global::" + package.Namespace + "." + groupName;
        source.Append("[assembly: global::AtomUI.Registration.ControlPackageMarker(").Append(L(package.Id)).Append(", typeof(").Append(group).AppendLine("), 1)]");
        // Conditional TypeMap annotations are interpreted by the pinned ILLink/ILC implementations.
        // Their experimental/trim diagnostics are suppressed only at these generated declarations.
        if (supportsTypeMap)
        {
            source.AppendLine("#pragma warning disable IL2026, IL3050, SYSLIB5004 // Conditional TypeMap metadata, consumed by ILLink/ILC.");
            foreach (var entry in mapEntries)
            {
                source.Append("[assembly: global::System.Runtime.InteropServices.TypeMap<").Append(group).Append(">(")
                    .Append(L(entry.Key)).Append(", typeof(global::").Append(package.Namespace).Append('.').Append(RegistrationNames.Proxy(entry.Control))
                    .Append("), typeof(").Append(entry.Trigger).AppendLine("))]");
            }
            source.AppendLine("#pragma warning restore IL2026, IL3050, SYSLIB5004");
        }
        source.Append("namespace ").Append(package.Namespace).AppendLine(";");
        source.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        source.Append("public sealed class ").Append(groupName).AppendLine("\n{");
        source.Append("    private ").Append(groupName).AppendLine("() { }");
        source.AppendLine("    // ABI v1: Browser backend resolves this helper from the marker's Group, never by a global short-name search.");
        source.AppendLine("    internal static class BrowserMap\n    {");
        source.AppendLine("        public static global::System.Collections.Generic.Dictionary<string, global::System.Type> Create() => new(global::System.StringComparer.Ordinal);");
        source.AppendLine("        public static void Add(global::System.Collections.Generic.Dictionary<string, global::System.Type> map, string key, global::System.RuntimeTypeHandle handle) => map.Add(key, global::System.Type.GetTypeFromHandle(handle)!);");
        source.AppendLine("        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
        source.AppendLine("        public static global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> Complete(global::System.Collections.Generic.Dictionary<string, global::System.Type> map) => map;");
        source.AppendLine("    }\n}");
        source.AppendLine("internal static partial class GeneratedControlPackageRegistration\n{");
        if (supportsTypeMap)
        {
            source.AppendLine("    private static readonly string[] CandidateKeys = new string[]\n    {");
            foreach (var entry in mapEntries)
            {
                source.Append("        ").Append(L(entry.Key)).AppendLine(",");
            }
            source.AppendLine("    };");
        }
        source.AppendLine("    internal static global::AtomUI.IAtomUIBuilder Register(global::AtomUI.IAtomUIBuilder builder,");
        source.AppendLine("        global::System.Func<global::AtomUI.Theme.Resources.IControlThemesProvider> createProvider,");
        source.AppendLine("        global::System.Action<global::AtomUI.IAtomUIBuilder>? prepare = null, global::System.Action<global::AtomUI.IAtomUIBuilder>? complete = null)");
        source.Append("        => global::AtomUI.Registration.ControlRegistrationRuntime.RegisterPackage(builder, ").Append(L(package.Id)).AppendLine(", createProvider, Collect, prepare, complete);");
        source.AppendLine("    internal static global::AtomUI.IAtomUIBuilder Ensure(global::AtomUI.IAtomUIBuilder builder,");
        source.AppendLine("        global::System.Func<global::AtomUI.Theme.Resources.IControlThemesProvider> createProvider,");
        source.AppendLine("        global::System.Action<global::AtomUI.IAtomUIBuilder>? prepare = null, global::System.Action<global::AtomUI.IAtomUIBuilder>? complete = null)");
        source.Append("        => global::AtomUI.Registration.ControlRegistrationRuntime.EnsurePackage(builder, ").Append(L(package.Id)).AppendLine(", createProvider, Collect, prepare, complete);");
        if (supportsTypeMap)
        {
            source.AppendLine("    private static void Collect(global::AtomUI.Registration.ControlPackageRegistrationBuilder builder)\n    {");
            source.AppendLine("        if (global::AtomUI.Registration.ControlRegistrationRuntime.IsTrimmed)\n        {");
            source.AppendLine("            global::AtomUI.Registration.ControlRegistrationRuntime.CollectFragments(builder, GetTypeMap(), CandidateKeys);");
            source.AppendLine("        }\n        else\n        {");
            foreach (var control in package.Controls)
            {
                source.Append("            new ").Append(RegistrationNames.Proxy(control)).AppendLine("().Add(builder);");
            }
            source.AppendLine("        }\n    }");
        }
        else
        {
            ConditionalRegistrationWriter.WriteCollector(source, package);
        }
        if (supportsTypeMap)
        {
            source.Append("    [global::AtomUI.Registration.GeneratedTypeMapAccessor(typeof(").Append(group).AppendLine("))]");
            source.Append("    [global::System.Diagnostics.CodeAnalysis.DynamicDependency(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods, typeof(").Append(group).AppendLine(".BrowserMap))]");
            source.AppendLine("    internal static global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> GetTypeMap()");
            source.Append("        => global::System.Runtime.InteropServices.TypeMapping.GetOrCreateExternalTypeMapping<").Append(group).AppendLine(">();");
        }
        source.AppendLine("}");
        foreach (var control in package.Controls)
        {
            var proxy = RegistrationNames.Proxy(control);
            source.Append('[').Append(proxy).AppendLine("]");
            source.Append("internal sealed class ").Append(proxy).AppendLine(" : global::AtomUI.Registration.ControlRegistrationFragmentAttribute\n{");
            if (control.TokenFactory is not null || control.SemanticFactory is not null)
            {
                source.AppendLine("    // The nested holder initializes only after this fragment's platform guards pass.");
                source.AppendLine("    private static class CachedDescriptors\n    {");
                if (control.TokenFactory is not null)
                {
                    WriteCachedDescriptor(source, "Token", "global::AtomUI.Theme.Schema.ControlTokenDescriptor",
                        "GeneratedThemeSchemaDescriptorFactory." + control.TokenFactory + "()");
                }
                if (control.SemanticFactory is not null)
                {
                    WriteCachedDescriptor(source, "Semantic", "global::AtomUI.Theme.Schema.ControlSemanticDescriptor",
                        "GeneratedSemanticPartManifest." + control.SemanticFactory + "()");
                }
                source.AppendLine("    }");
            }
            source.Append("    public override string FragmentId => ").Append(L(package.Id + ":" + control.Type.AssemblyQualifiedName)).AppendLine(";");
            source.AppendLine("    public override void Add(global::AtomUI.Registration.ControlPackageRegistrationBuilder builder)\n    {");
            foreach (var guard in control.Guards)
            {
                source.Append("        if (").Append(guard).AppendLine(") return;");
            }

            if (control.TokenFactory is not null)
            {
                source.AppendLine("        builder.AddControl(CachedDescriptors.Token);");
            }

            if (control.SemanticFactory is not null)
            {
                source.AppendLine("        builder.AddSemanticControl(CachedDescriptors.Semantic);");
            }

            foreach (var asset in package.Assets.Where(a => control.Assets.Contains(a.Id)))
            {
                WriteAssetReference(source, asset, "        ");
            }

            source.AppendLine("    }\n}");
        }
        source.AppendLine("internal static class GeneratedRegistrationFactories\n{");
        if (package.Assets.Any(asset => asset.Exports.Count != 0))
        {
            source.AppendLine("    // Compile-time global schema evidence: strings only, no Type or factory roots.");
            source.AppendLine("    private static readonly string[] CompiledGlobalTokenNames = new string[]\n    {");
            foreach (var name in package.CompiledGlobalTokenNames)
            {
                source.Append("        ").Append(L(name)).AppendLine(",");
            }

            source.AppendLine("    };");
        }
        foreach (var asset in package.Assets)
        {
            source.Append("    internal static void AddAsset_").Append(RegistrationNames.Hash(asset.Id)).AppendLine("(global::AtomUI.Registration.ControlPackageRegistrationBuilder builder)\n    {");
            foreach (var guard in asset.Guards)
            {
                source.Append("        if (").Append(guard).AppendLine(") return;");
            }

            WriteAssetRegistration(source, asset, "        ");
            source.AppendLine("    }");
            source.Append("    internal static global::Avalonia.Controls.IResourceProvider ").Append(RegistrationNames.AssetFactory(asset.Id)).Append("() => new ").Append(asset.Wrapper).AppendLine("();");
            source.Append("    internal static global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor ").Append(RegistrationNames.AssetDescriptor(asset.Id)).AppendLine("() => global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor.CreateGenerated(");
            source.Append("        ").Append(L(asset.Id)).Append(", new global::System.Uri(").Append(L(asset.Uri)).AppendLine("),");
            source.AppendLine("        new global::AtomUI.Theme.Schema.ControlThemeExportDescriptor[]\n        {");
            foreach (var export in asset.Exports)
            {
                source.Append("            new(typeof(").Append(export.Target.Name).Append("), ").Append(export.KeyType is null ? L(export.Key!) : "typeof(" + export.KeyType.Name + ")").AppendLine("),");
            }

            source.AppendLine("        },\n        new global::AtomUI.Theme.Schema.ControlTokenIdentity[]\n        {");
            foreach (var owner in asset.Owners)
            {
                source.Append("            ").Append(Identity(owner)).AppendLine(",");
            }

            source.AppendLine("        },\n        new global::AtomUI.Theme.Schema.ControlThemeBindingDescriptor[]\n        {");
            foreach (var binding in asset.Bindings)
            {
                source.Append("            new(").Append(Identity(binding.Owner)).Append(", ").Append(L(binding.Property)).Append(", typeof(").Append(binding.Target.Name).AppendLine(")),");
            }

            source.Append("        }, CompiledGlobalTokenNames, 0x").Append(asset.CompiledContractFingerprint.ToString("X16")).AppendLine("UL);");
            source.Append("    private static class CachedAsset_").Append(RegistrationNames.Hash(asset.Id)).AppendLine("\n    {");
            WriteCachedDescriptor(source, "Descriptor", "global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor",
                RegistrationNames.AssetDescriptor(asset.Id) + "()");
            WriteCachedDescriptor(source, "Resource", "global::AtomUI.Registration.ControlThemeResourceRegistration",
                "new global::AtomUI.Registration.ControlThemeResourceRegistration(" + L(asset.Id) + ", global::AtomUI.Registration.ControlResourcePhase.Control, " +
                asset.Order + ", " + RegistrationNames.AssetFactory(asset.Id) + ")");
            source.AppendLine("    }");
        }
        source.AppendLine("}");
        return source.ToString();
    }
    private static void WriteAssetReference(StringBuilder source, RegistrationAsset asset, string indent) =>
        source.Append(indent).Append("GeneratedRegistrationFactories.AddAsset_").Append(RegistrationNames.Hash(asset.Id)).AppendLine("(builder);");

    private static void WriteAssetRegistration(StringBuilder source, RegistrationAsset asset, string indent)
    {
        source.Append(indent).Append("builder.AddThemeAsset(CachedAsset_").Append(RegistrationNames.Hash(asset.Id))
            .Append(".Descriptor, CachedAsset_").Append(RegistrationNames.Hash(asset.Id)).AppendLine(".Resource);");
    }
    private static void WriteCachedDescriptor(StringBuilder source, string name, string type, string expression)
    {
        var field = "_" + char.ToLowerInvariant(name[0]) + name.Substring(1);
        // A failed factory call must retain its original exception type. Concurrent first calls may
        // construct twice, but every builder receives the same published immutable descriptor.
        source.Append("        private static ").Append(type).Append("? ").Append(field).AppendLine(";");
        source.Append("        internal static ").Append(type).Append(' ').Append(name).AppendLine("\n        {");
        source.AppendLine("            get\n            {");
        source.Append("                var cached = global::System.Threading.Volatile.Read(ref ").Append(field).AppendLine(");");
        source.AppendLine("                if (cached is not null) return cached;");
        source.Append("                var created = ").Append(expression).AppendLine(";");
        source.Append("                return global::System.Threading.Interlocked.CompareExchange(ref ").Append(field)
            .AppendLine(", created, null) ?? created;");
        source.AppendLine("            }\n        }");
    }
    private static string Identity(RegistrationOwner owner) => "global::AtomUI.Theme.Schema.ControlTokenIdentity.ForControl(typeof(" + owner.Type.Name + "), " + L(owner.Catalog) + ", " + L(owner.Id) + ")";
    private static (IReadOnlyList<TypeMapEntry> Entries, IReadOnlyList<string> Collisions) CreateMapEntries(
        RegistrationPackage package,
        string groupName,
        Func<string, string> keyHash)
    {
        var groupIdentity = package.AssemblyIdentity + "|" + package.Namespace + "." + groupName;
        var identities = new Dictionary<string, string>(StringComparer.Ordinal);
        var entries = new List<TypeMapEntry>();
        var collisions = new List<string>();
        foreach (var control in package.Controls)
        {
            foreach (var trigger in control.Triggers)
        {
            var fullIdentity = groupIdentity + "\n" + control.Type.AssemblyQualifiedName + "\n" + trigger;
            var key = RegistrationNames.TypeMapKey(
                groupIdentity,
                control.Type.AssemblyQualifiedName,
                trigger,
                keyHash);
            if (identities.TryGetValue(key, out var existing) && existing != fullIdentity)
            {
                collisions.Add($"TypeMap key collision '{key}' between '{existing}' and '{fullIdentity}'.");
                continue;
            }

            identities[key] = fullIdentity;
            entries.Add(new(control, trigger, key));
        }
        }

        return (entries, collisions);
    }

    private sealed record TypeMapEntry(RegistrationControl Control, string Trigger, string Key);
    private static string L(string value) => RegistrationNames.Literal(value);
}
