using System.Text;
using AtomUI.SourceGeneration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace AtomUI.Generator;

internal sealed class GeneratedThemeSchemaWriter
{
    private readonly GenerationOutput _context;
    private readonly string _generatedNamespace;
    private readonly string _controlCatalog;
    private readonly IReadOnlyList<SchemaTokenInfo> _globalTokens;
    private readonly IReadOnlyList<ControlThemeInfo> _controls;
    private readonly IReadOnlyList<ThemeAlgorithmInfo> _algorithms;

    internal GeneratedThemeSchemaWriter(
        GenerationOutput context,
        string? assemblyName,
        string controlCatalog,
        IEnumerable<SchemaTokenInfo> globalTokens,
        IEnumerable<ControlThemeInfo> controls,
        IEnumerable<ThemeAlgorithmInfo> algorithms)
    {
        _context = context;
        _generatedNamespace = GeneratedCodeNamespace.ForAssembly(assemblyName);
        _controlCatalog = controlCatalog;
        _globalTokens = globalTokens.OrderBy(static token => token.Name, StringComparer.Ordinal).ToArray();
        _controls = controls.OrderBy(static control => control.ControlName, StringComparer.Ordinal)
                            .ToArray();
        _algorithms = algorithms.OrderBy(static algorithm => algorithm.AlgorithmValue)
                                .ThenBy(static algorithm => algorithm.TypeName, StringComparer.Ordinal)
                                .ToArray();
    }

    internal void Write()
    {
        _context.AddSource(
            "GeneratedThemeSchema.g.cs",
            GeneratedSourceText.From(BuildSource()));
    }

    private string BuildSource()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("using global::AtomUI.Theme.Schema;");
        source.AppendLine();
        source.Append("namespace ").Append(_generatedNamespace).AppendLine(";");
        source.AppendLine();
        source.AppendLine("internal static class GeneratedThemeSchema");
        source.AppendLine("{");
        WriteGlobalTokens(source);
        source.AppendLine();
        WriteAlgorithms(source);
        source.AppendLine();
        source.AppendLine("    internal static global::System.Collections.Generic.IReadOnlyList<TokenDescriptor> GetGlobalTokens() => s_globalTokens;");

        source.AppendLine("    internal static global::System.Collections.Generic.IReadOnlyList<ThemeAlgorithmDescriptor> GetAlgorithms() => s_algorithms;");
        source.AppendLine("}");
        source.AppendLine();
        WriteDescriptorFactory(source);
        return source.ToString();
    }

    private void WriteGlobalTokens(StringBuilder source)
    {
        source.AppendLine("    private static readonly TokenDescriptor[] s_globalTokens = new TokenDescriptor[]");
        source.AppendLine("    {");
        foreach (var token in _globalTokens)
        {
            source.Append("        GeneratedThemeSchemaDescriptorFactory.")
                  .Append(GetGlobalTokenDescriptorFactoryMethodName(token))
                  .AppendLine("(),");
        }
        source.AppendLine("    };");
    }

    private void WriteDescriptorFactory(StringBuilder source)
    {
        source.AppendLine("internal static class GeneratedThemeSchemaDescriptorFactory");
        source.AppendLine("{");
        for (var slot = 0; slot < _globalTokens.Count; slot++)
        {
            var token = _globalTokens[slot];
            source.Append("    internal static TokenDescriptor ")
                  .Append(GetGlobalTokenDescriptorFactoryMethodName(token))
                  .AppendLine("()");
            source.AppendLine("    {");
            source.AppendLine("        return");
            WriteToken(
                source,
                token,
                slot,
                $"global::AtomUI.Theme.Resources.SharedTokenKind.{token.Name}",
                GlobalTokenAccessorName,
                "            ",
                ";");
            source.AppendLine("    }");
            source.AppendLine();
        }

        foreach (var control in _controls.Where(static control => control.HasDescriptor))
        {
            source.Append("    internal static ControlTokenDescriptor ")
                  .Append(GetControlDescriptorFactoryMethodName(control))
                  .AppendLine("()");
            source.AppendLine("    {");
            source.AppendLine("        return");
            WriteControlDescriptor(source, control, "            ", ";");
            source.AppendLine("    }");
            source.AppendLine();
        }
        source.AppendLine("}");

        if (_globalTokens.Count != 0)
        {
            source.AppendLine();
            WriteAccessor(source, GlobalTokenAccessorName, _globalTokens);
        }
        foreach (var control in _controls.Where(static control => control.HasDescriptor && control.HasOwnToken))
        {
            var tokens = OrderedOwnTokens(control);
            if (tokens.Count == 0)
            {
                continue;
            }
            source.AppendLine();
            WriteAccessor(source, GetControlTokenAccessorName(control), tokens);
        }
    }

    // One accessor per token class keeps descriptors free of per-token delegates; an accessor is referenced only
    // from its own descriptor factory, so it is trimmed together with an unused control descriptor.
    private static void WriteAccessor(StringBuilder source, string className, IReadOnlyList<SchemaTokenInfo> tokens)
    {
        const string tokenType = "global::AtomUI.Theme.DesignTokens.AbstractDesignToken";
        source.Append("internal sealed class ").Append(className).AppendLine(" : TokenValueAccessor");
        source.AppendLine("{");
        source.Append("    internal static readonly ").Append(className).Append(" Instance = new ")
              .Append(className).AppendLine("();");
        source.AppendLine();
        source.Append("    public override object GetValue(").Append(tokenType).AppendLine(" token, int slot)");
        WriteSwitch(source, tokens, static (builder, token) => builder
            .Append("return ((").Append(token.DeclaringType).Append(")token).").Append(token.Name).Append(';'));
        source.AppendLine();
        source.Append("    public override void SetValue(").Append(tokenType).AppendLine(" token, int slot, object value)");
        WriteSwitch(source, tokens, static (builder, token) => builder
            .Append("((").Append(token.DeclaringType).Append(")token).").Append(token.Name)
            .Append(" = (").Append(token.ValueType).Append(")value!; return;"));
        source.AppendLine();
        source.Append("    public override object ProjectResourceValue(").Append(tokenType).AppendLine(" token, int slot)");
        WriteSwitch(source, tokens, static (builder, token) => builder
            .Append("return global::AtomUI.Theme.Schema.ThemeResourceValue.Project(((").Append(token.DeclaringType)
            .Append(")token).").Append(token.Name).Append(");"));
        source.AppendLine("}");
    }

    private static void WriteSwitch(
        StringBuilder source,
        IReadOnlyList<SchemaTokenInfo> tokens,
        Action<StringBuilder, SchemaTokenInfo> writeCase)
    {
        source.AppendLine("    {");
        source.AppendLine("        switch (slot)");
        source.AppendLine("        {");
        for (var slot = 0; slot < tokens.Count; slot++)
        {
            source.Append("            case ").Append(slot).Append(": ");
            writeCase(source, tokens[slot]);
            source.AppendLine();
        }
        source.AppendLine("            default: throw new global::System.ArgumentOutOfRangeException(nameof(slot));");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    private void WriteControlDescriptor(
        StringBuilder source,
        ControlThemeInfo control,
        string indentation,
        string suffix)
    {
        var catalog = SymbolDisplay.FormatLiteral(_controlCatalog, quote: true);
        var id = SymbolDisplay.FormatLiteral(control.ControlName, quote: true);
        var controlType = FullyQualify(control.ControlTypeName);
        source.Append(indentation).AppendLine("new ControlTokenDescriptor(");
        source.Append(indentation).Append("    typeof(").Append(controlType).AppendLine("),");
        if (!control.HasOwnToken)
        {
            source.Append(indentation).Append("    ControlTokenIdentity.ForControl(typeof(").Append(controlType).Append("), ")
                  .Append(catalog).Append(", ").Append(id).AppendLine(")");
            source.Append(indentation).Append(')').AppendLine(suffix);
            return;
        }

        source.Append(indentation).Append("    ControlTokenIdentity.ForControl(typeof(").Append(controlType).Append("), ")
              .Append(catalog).Append(", ").Append(id).AppendLine("),");
        var typeName = FullyQualify(control.OwnToken!.GetFullyQualifiedTokenTypeName());
        source.Append(indentation).AppendLine("    new TokenDescriptor[]");
        source.Append(indentation).AppendLine("    {");
        var tokens = OrderedOwnTokens(control);
        var accessor = GetControlTokenAccessorName(control);
        for (var slot = 0; slot < tokens.Count; slot++)
        {
            var resourceKey = $"global::{control.ControlNamespace}.DesignTokens.{control.TokenKindType}.{tokens[slot].Name}";
            WriteToken(source, tokens[slot], slot, resourceKey, accessor, indentation + "        ");
        }
        source.Append(indentation).AppendLine("    },");
        source.Append(indentation).Append("    static () => new ").Append(typeName).AppendLine("(),");
        source.Append(indentation).Append("    static (token, appearance) => ((").Append(typeName)
              .AppendLine(")token).CalculateTokenValues(appearance == global::AtomUI.Theme.ThemeAppearance.Dark)");
        source.Append(indentation).Append(')').AppendLine(suffix);
    }

    private void WriteAlgorithms(StringBuilder source)
    {
        source.AppendLine("    private static readonly ThemeAlgorithmDescriptor[] s_algorithms = new ThemeAlgorithmDescriptor[]");
        source.AppendLine("    {");
        foreach (var algorithm in _algorithms)
        {
            source.Append("        new ThemeAlgorithmDescriptor(global::AtomUI.Theme.Algorithms.ThemeAlgorithm.")
                  .Append(algorithm.Algorithm)
                  .Append(", ").Append(algorithm.Revision)
                  .Append(", ThemeAppearanceEffect.").Append(algorithm.AppearanceEffect).AppendLine(",");
            source.Append("            static () => new ").Append(algorithm.TypeName).AppendLine("()),");
        }
        source.AppendLine("    };");
    }

    private static void WriteToken(
        StringBuilder source,
        SchemaTokenInfo token,
        int slot,
        string resourceKey,
        string accessor,
        string indentation = "        ",
        string suffix = ",")
    {
        var name = SymbolDisplay.FormatLiteral(token.Name, quote: true);
        source.Append(indentation).Append("TokenDescriptor.CreateGenerated(").Append(name).Append(", ").Append(slot)
              .Append(", TokenStage.").Append(token.Stage)
              .Append(", TokenValueCodec<").Append(token.ValueType).Append(">.Instance, ")
              .Append(resourceKey).Append(", ").Append(accessor).Append(".Instance)").AppendLine(suffix);
    }

    private static IReadOnlyList<SchemaTokenInfo> OrderedOwnTokens(ControlThemeInfo control) =>
        control.OwnSchemaTokens.OrderBy(static token => token.Name, StringComparer.Ordinal).ToArray();

    private const string GlobalTokenAccessorName = "GeneratedGlobalTokenAccessor";

    private static string GetGlobalTokenDescriptorFactoryMethodName(SchemaTokenInfo token)
    {
        return $"CreateGlobalTokenDescriptor_{token.Name}";
    }

    internal static string GetControlDescriptorFactoryMethodName(ControlThemeInfo control)
    {
        return $"CreateControlDescriptor_{ToIdentifier(control.ControlName)}_{ComputeHash(control.ControlMetadataName):X16}";
    }

    private static string GetControlTokenAccessorName(ControlThemeInfo control)
    {
        return $"GeneratedTokenAccessor_{ToIdentifier(control.ControlName)}_{ComputeHash(control.ControlMetadataName):X16}";
    }

    private static string ToIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length + 1);
        foreach (var character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }
        if (builder.Length == 0 || char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }
        return builder.ToString();
    }

    private static ulong ComputeHash(string value)
    {
        var hash = 14695981039346656037UL;
        foreach (var character in value)
        {
            hash ^= character;
            hash *= 1099511628211UL;
        }
        return hash;
    }

    private static string FullyQualify(string typeName)
    {
        return typeName.StartsWith("global::", StringComparison.Ordinal)
            ? typeName
            : $"global::{typeName}";
    }
}
